### ISSUE TITLE
Múltiplos restaurantes na consulta 

### ISSUE THREAD

**Issue by vafjr87** [Kasama/bandejao-bot#1]
Bom dia, Kasama!

Seria interessante poder selecionar mais de um cardápio para visualizar a cada consulta. Na Cidade Universitária, por exemplo, há vários bandejões e muitos alunos costumam escolher a qual ir de acordo com o cardápio oferecido. A forma como o bot funciona atualmente dificulta bastante essa consulta.

**Comment by Kasama** [comment]
Olá vafjr87,

Primeiramente obrigado pelo feedback, eu realmente não tinha pensado nessa possibilidade, mas gostei bastante da ideia, vou ver se consigo implementar até a semana que vem algo que adicione essa funcionalidade.

**Comment by vafjr87** [comment]
Fico muito grato, Kasama! Assim que isso estiver pronto, vou aproveitar pra divulgar pela EACH e para os amigos que são da Cidade Universitária e usam o Telegram!

**Comment by vafjr87** [comment]
Esquece de nóis, não :~

**Comment by Kasama** [comment]
desculpe a demora @vafjr87, não esqueci da issue e estou trabalhando nela no meu tempo livre. Infelizmente esses últimos meses foram bastante caóticos pra min, e meu tempo livre ficou muito reduzido por vários motivos pessoais. Agradeço muito a paciência e saiba que o projeto não está morto =)

**Comment by Kasama** [comment]
Finalmente essa feature foi implementada @vafjr87, me desculpe pela demora e muito obrigado pela paciência.

Qualquer problema encontrado ou nova sugestão, por favor entre em contato.
