### ISSUE TITLE
Impossível remover Lorena da seleção dos restaurantes

### ISSUE THREAD

**Issue by tiagotriques** [Kasama/bandejao-bot#14]
O Campus de Lorena tem 2 restaurantes cadastrados:
  - Lorena, Lorena
  - Lorena, Eel   área I

Ao tentar remover "Lorena", apenas o último é removido
e o restaurante "Lorena, Lorena" manda o cardápio do Campus 1 da USP São Carlos:

Tiago Esperança Triques, [09.03.18 10:47]
⚙️ Configurações

Bandejao, [09.03.18 10:47]
Restaurantes selecionados:
  - Lorena, Lorena
Selecione uma opção

Tiago Esperança Triques, [09.03.18 10:47]
☀️ Almoço

Bandejao, [09.03.18 10:47]
🏫 São Carlos, Área 1 🍽
☀️ Almoço de Sexta (09/03):
Arroz/Feijão/Arroz Integral
Saladas Diversas
Hambúrguer ao molho pizzaiolo
Opção Vegetariana: Hambúrguer de PVT
Macarrão ao sugo
Sorvete de abacaxi
Banana
Minipão 
Suco

Valor energético médio: ⚡️ 1613Kcal

**Comment by Kasama** [comment]
Vou investigar, aqui só apareceu um restaurante de Lorena (Eel I). O campus tem dois restaurantes mesmo?

**Comment by tiagotriques** [comment]
São 2 campus em Lorena, cada um com seu [restaurante.](http://site.eel.usp.br/comunidade/alunos/coseas/coseas)

**Comment by Kasama** [comment]
Pelo que me parece, eles mudaram o nome do restaurante de lorena na API da usp.

Antes era só Lorena, agora é Eel I.

Dei uma olhada no banco de dados e esse problema só aconteceu com umas 5 pessoas (incluindo você), vou arrumar "na mão" pra vcs.

Vou pensar em alguma forma de manter consistência caso eles mudem o nome de algum restaurante novamente.

Obrigado pelo feedback! Eu te aviso quando estiver resolvido.

**Comment by Kasama** [comment]
Eita, cada campus tem um restaurante com cardápios diferentes? Por que a API da USP só mostra um deles, se for isso temos um problema maior

**Comment by tiagotriques** [comment]
Pelo que entendi é o mesmo cardápio pros 2

**Comment by Kasama** [comment]
Nesse caso faz sentido só existir um na API. Vou resolver "na mão" aqui e  já te dou um toque :+1:

**Comment by Kasama** [comment]
Resolvido!

Vou pensar em uma forma de isso não acontecer de novo!
