### ISSUE TITLE
Não mostra o cardápio de domingo automaticamente

### ISSUE THREAD

**Issue by felipe-dachshund** [Kasama/bandejao-bot#22]
O bot não mostra o cardápio de domingo automaticamente para os grupos inscritos.

**Comment by felipe-dachshund** [comment]
Muito obrigado por colocar o cardápio de domingo, mas ainda tem um problema: o bot está mostrando o cardápio da janta no horário do almoço no domingo

**Comment by Kasama** [comment]
Dessa semana funcionou corretamente?

**Comment by felipe-dachshund** [comment]
Ah, sim, funcionou direitinho ontem, já pode fechar a issue :)
