### ISSUE TITLE
Bot não responde nem envia mais as mensagens automáticas

### ISSUE THREAD

**Issue by irlalmeida** [Kasama/bandejao-bot#24]
Desde o dia 11/10 o bot não envia mais automaticamente as mensagens no privado ou em grupos que foi adicionado, e também não responde mais quando perguntado sobre o cardápio, seja almoço, jantar ou próximo

**Comment by Kasama** [comment]
Olá Isabela! Obrigado pelo report. Eu tive que migrar o bot do heroku pro fly.io, por que o heroku vai [acabar com o plano gratuito](https://devcenter.heroku.com/changelog-items/2461). Parece que os limites de memoria do fly.io são bem mais baixos e ele fica matando o bot.

Eu estou olhando o que eu posso fazer e procurando alternativas. Vou colocando updates aqui na thread.

**Comment by Kasama** [comment]
Eu temporariamente voltei o bot pro Heroku enquanto resolvo definitivamente. Tenho até o fim de novembro pra isso :smile:.

Por favor me avise se voltar a ter problemas parecidos

**Comment by Kasama** [comment]
Deve estar funcionando normalmente agora. Eu reescrevi o bot e movi ele pro fly.io. Qualquer novo problema manda uma issue, pls :smile:
