### ISSUE TITLE
Problema na codificação de caracteres nos nomes dos campi/bandejões

### ISSUE THREAD

**Issue by felipe-dachshund** [Kasama/bandejao-bot#25]
Uma atualização recente afetou a codificação de caracteres nos nomes dos campi e dos bandejões. Com isso, além de os nomes novos aparecerem errados, não é mais possível remover os nomes antigos da seleção, e o bot mostra o cardápio da Área 1 de São Carlos pra eles.![IMG_20221025_114121.jpg](https://user-images.githubusercontent.com/24244517/197806362-62241cce-ecee-4345-a504-b444312d2349.jpg)

**Comment by Kasama** [comment]
@felipe-dachshund can you try it out now? I've ran a script to migrate the configs to the new name (unfortunately keeping the � there).

This should be better in the near future with some work I'm doing regarding a future platform migration from heroku to fly.io.

**Comment by felipe-dachshund** [comment]
Well, since you want to talk in english, I'll try to answer in english too (just a try).

At first, the bot replied the menus duplicated, so I deselected each restaurant and selected them again. Everything is working now.

**Comment by Kasama** [comment]
Perdão, eu tava falando em ingles com outra pessoa do trabalho e me embananei :smile: 

Bom saber que funcionou. Obrigado pelo report de novo!
